### ISSUE TITLE
Would be nice if DnsRecordName can be set by a parameter

### ISSUE THREAD

**Issue by einwaschdl** [kutzilla/docker-hetzner-ddns#4]
I only want to point a sub domain to my dynamic ip at home. Therefor it would be nice if DnsRecordName can also be set by a parameter.

Other then that nice work and thanks for sharing it :-)

**Comment by kutzilla** [comment]
This feature is now included in the latest release v.1.2. You can set the environment variable RECORD_NAME to specify a subdomain for DDNS updates.
